# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_m02f6b5bb52bf319dfe0fa8bf2cbbf84b', [dirname(__file__)])
        except ImportError:
            import _m02f6b5bb52bf319dfe0fa8bf2cbbf84b
            return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b
        if fp is not None:
            try:
                _mod = imp.load_module('_m02f6b5bb52bf319dfe0fa8bf2cbbf84b', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _m02f6b5bb52bf319dfe0fa8bf2cbbf84b = swig_import_helper()
    del swig_import_helper
else:
    import _m02f6b5bb52bf319dfe0fa8bf2cbbf84b
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator_equal(self, x)

    def copy(self):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator_copy(self)

    def next(self):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator_next(self)

    def __next__(self):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator___next__(self)

    def previous(self):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator_previous(self)

    def advance(self, n):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    all_keys = [attr for attr in dir(class_type) if not attr.startswith('__')and attr != '_s' ]
    data_keys = sorted(class_type.__swig_setmethods__.keys())
    method_keys = [ x for x in all_keys if x not in data_keys ]
    raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
     (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
# this line is changed to handle older swigs that used PySwigObject instead of the current SwigPyObject
        if type(value).__name__ == 'SwigPyObject' or type(value).__name__ == 'PySwigObject' :
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        all_keys = [attr for attr in dir(class_type) if not attr.startswith('__') and attr != '_s' ]
        data_keys = sorted(class_type.__swig_setmethods__.keys())
        method_keys = [ x for x in all_keys if x not in data_keys ]
        raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
         (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,1)

import sim_services
import me1e67967e8035ed4a8ef037c1d62200e
import meade57f199c86184507d5c153bb0ff30
class SimEnvironment(sim_services.Environment):
    __swig_setmethods__ = {}
    for _s in [sim_services.Environment]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SimEnvironment, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.Environment]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SimEnvironment, name)
    __repr__ = _swig_repr

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_SimEnvironment()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SimEnvironment", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SimEnvironment___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SimEnvironment___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_SimEnvironment
    __del__ = lambda self: None
SimEnvironment_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SimEnvironment_swigregister
SimEnvironment_swigregister(SimEnvironment)


def exec_collect_init(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.exec_collect_init(*args)
exec_collect_init = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.exec_collect_init
class SysSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SysSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SysSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sched"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SysSimObject_sched_set
    __swig_getmethods__["sched"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SysSimObject_sched_get
    if _newclass:
        sched = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SysSimObject_sched_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SysSimObject_sched_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_SysSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SysSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SysSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SysSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SysSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SysSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_SysSimObject
    __del__ = lambda self: None
SysSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SysSimObject_swigregister
SysSimObject_swigregister(SysSimObject)

class MonteCarloSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MonteCarloSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, MonteCarloSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mc"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MonteCarloSimObject_mc_set
    __swig_getmethods__["mc"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MonteCarloSimObject_mc_get
    if _newclass:
        mc = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MonteCarloSimObject_mc_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MonteCarloSimObject_mc_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_MonteCarloSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MonteCarloSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MonteCarloSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MonteCarloSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MonteCarloSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MonteCarloSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_MonteCarloSimObject
    __del__ = lambda self: None
MonteCarloSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MonteCarloSimObject_swigregister
MonteCarloSimObject_swigregister(MonteCarloSimObject)

class MemoryManagerSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MemoryManagerSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, MemoryManagerSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mm"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MemoryManagerSimObject_mm_set
    __swig_getmethods__["mm"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MemoryManagerSimObject_mm_get
    if _newclass:
        mm = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MemoryManagerSimObject_mm_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MemoryManagerSimObject_mm_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_MemoryManagerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MemoryManagerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MemoryManagerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MemoryManagerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MemoryManagerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MemoryManagerSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_MemoryManagerSimObject
    __del__ = lambda self: None
MemoryManagerSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MemoryManagerSimObject_swigregister
MemoryManagerSimObject_swigregister(MemoryManagerSimObject)

class CheckPointRestartSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CheckPointRestartSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, CheckPointRestartSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cpr"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CheckPointRestartSimObject_cpr_set
    __swig_getmethods__["cpr"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CheckPointRestartSimObject_cpr_get
    if _newclass:
        cpr = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CheckPointRestartSimObject_cpr_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CheckPointRestartSimObject_cpr_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_CheckPointRestartSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "CheckPointRestartSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CheckPointRestartSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CheckPointRestartSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CheckPointRestartSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CheckPointRestartSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_CheckPointRestartSimObject
    __del__ = lambda self: None
CheckPointRestartSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CheckPointRestartSimObject_swigregister
CheckPointRestartSimObject_swigregister(CheckPointRestartSimObject)

class SieSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SieSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SieSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sie"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SieSimObject_sie_set
    __swig_getmethods__["sie"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SieSimObject_sie_get
    if _newclass:
        sie = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SieSimObject_sie_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SieSimObject_sie_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_SieSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SieSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SieSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SieSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SieSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SieSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_SieSimObject
    __del__ = lambda self: None
SieSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.SieSimObject_swigregister
SieSimObject_swigregister(SieSimObject)

class CommandLineArgumentsSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CommandLineArgumentsSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, CommandLineArgumentsSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cmd_args"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CommandLineArgumentsSimObject_cmd_args_set
    __swig_getmethods__["cmd_args"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CommandLineArgumentsSimObject_cmd_args_get
    if _newclass:
        cmd_args = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CommandLineArgumentsSimObject_cmd_args_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CommandLineArgumentsSimObject_cmd_args_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_CommandLineArgumentsSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "CommandLineArgumentsSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CommandLineArgumentsSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CommandLineArgumentsSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CommandLineArgumentsSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CommandLineArgumentsSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_CommandLineArgumentsSimObject
    __del__ = lambda self: None
CommandLineArgumentsSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.CommandLineArgumentsSimObject_swigregister
CommandLineArgumentsSimObject_swigregister(CommandLineArgumentsSimObject)

class MessageSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MessageSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, MessageSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mpublisher"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mpublisher_set
    __swig_getmethods__["mpublisher"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mpublisher_get
    if _newclass:
        mpublisher = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mpublisher_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mpublisher_set)
    __swig_setmethods__["mcout"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mcout_set
    __swig_getmethods__["mcout"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mcout_get
    if _newclass:
        mcout = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mcout_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mcout_set)
    __swig_setmethods__["mtcout"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mtcout_set
    __swig_getmethods__["mtcout"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mtcout_get
    if _newclass:
        mtcout = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mtcout_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mtcout_set)
    __swig_getmethods__["mfile"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mfile_get
    if _newclass:
        mfile = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mfile_get)
    __swig_setmethods__["mdevice"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mdevice_set
    __swig_getmethods__["mdevice"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mdevice_get
    if _newclass:
        mdevice = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mdevice_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_mdevice_set)
    __swig_getmethods__["pfile"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_pfile_get
    if _newclass:
        pfile = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_pfile_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_MessageSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MessageSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_MessageSimObject
    __del__ = lambda self: None
MessageSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MessageSimObject_swigregister
MessageSimObject_swigregister(MessageSimObject)

class JITSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, JITSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, JITSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["jit"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.JITSimObject_jit_set
    __swig_getmethods__["jit"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.JITSimObject_jit_get
    if _newclass:
        jit = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.JITSimObject_jit_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.JITSimObject_jit_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_JITSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "JITSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.JITSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.JITSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.JITSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.JITSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_JITSimObject
    __del__ = lambda self: None
JITSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.JITSimObject_swigregister
JITSimObject_swigregister(JITSimObject)

class InputProcessorSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, InputProcessorSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, InputProcessorSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ip"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_ip_set
    __swig_getmethods__["ip"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_ip_get
    if _newclass:
        ip = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_ip_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_ip_set)
    __swig_setmethods__["mtv"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_mtv_set
    __swig_getmethods__["mtv"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_mtv_get
    if _newclass:
        mtv = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_mtv_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_mtv_set)
    __swig_setmethods__["units_map_ptr"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_units_map_ptr_set
    __swig_getmethods__["units_map_ptr"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_units_map_ptr_get
    if _newclass:
        units_map_ptr = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_units_map_ptr_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_units_map_ptr_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_InputProcessorSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InputProcessorSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_InputProcessorSimObject
    __del__ = lambda self: None

    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject___len__(self, *args)
InputProcessorSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InputProcessorSimObject_swigregister
InputProcessorSimObject_swigregister(InputProcessorSimObject)

class ThreadProcessEventSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ThreadProcessEventSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ThreadProcessEventSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ep"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ThreadProcessEventSimObject_ep_set
    __swig_getmethods__["ep"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ThreadProcessEventSimObject_ep_get
    if _newclass:
        ep = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ThreadProcessEventSimObject_ep_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ThreadProcessEventSimObject_ep_set)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_ThreadProcessEventSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "ThreadProcessEventSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ThreadProcessEventSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ThreadProcessEventSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ThreadProcessEventSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ThreadProcessEventSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_ThreadProcessEventSimObject
    __del__ = lambda self: None
ThreadProcessEventSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ThreadProcessEventSimObject_swigregister
ThreadProcessEventSimObject_swigregister(ThreadProcessEventSimObject)

class EventManagerSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EventManagerSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, EventManagerSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["em"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_em_set
    __swig_getmethods__["em"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_em_get
    if _newclass:
        em = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_em_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_em_set)
    __swig_setmethods__["ep"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_ep_set
    __swig_getmethods__["ep"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_ep_get
    if _newclass:
        ep = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_ep_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_ep_set)
    __swig_setmethods__["thread_process_event_so"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_thread_process_event_so_set
    __swig_getmethods__["thread_process_event_so"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_thread_process_event_so_get
    if _newclass:
        thread_process_event_so = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_thread_process_event_so_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_thread_process_event_so_set)

    def create_thread_process_event(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_create_thread_process_event(self, *args)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_EventManagerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "EventManagerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_EventManagerSimObject
    __del__ = lambda self: None
EventManagerSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.EventManagerSimObject_swigregister
EventManagerSimObject_swigregister(EventManagerSimObject)

class VariableServerSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, VariableServerSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, VariableServerSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["vs"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_vs_set
    __swig_getmethods__["vs"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_vs_get
    if _newclass:
        vs = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_vs_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_vs_set)
    __swig_getmethods__["sim_control_panel"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_sim_control_panel_get
    if _newclass:
        sim_control_panel = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_sim_control_panel_get)
    __swig_getmethods__["trick_view"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_trick_view_get
    if _newclass:
        trick_view = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_trick_view_get)
    __swig_getmethods__["malfunctions_trick_view"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_malfunctions_trick_view_get
    if _newclass:
        malfunctions_trick_view = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_malfunctions_trick_view_get)
    __swig_getmethods__["stripchart"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_stripchart_get
    if _newclass:
        stripchart = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_stripchart_get)
    __swig_getmethods__["monte_monitor"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_monte_monitor_get
    if _newclass:
        monte_monitor = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_monte_monitor_get)

    def monte_carlo_disable_all_apps(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_monte_carlo_disable_all_apps(self, *args)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_VariableServerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "VariableServerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_VariableServerSimObject
    __del__ = lambda self: None
VariableServerSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.VariableServerSimObject_swigregister
VariableServerSimObject_swigregister(VariableServerSimObject)

class DataRecordDispatcherSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DataRecordDispatcherSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, DataRecordDispatcherSimObject, name)
    __repr__ = _swig_repr
    __swig_getmethods__["drd"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DataRecordDispatcherSimObject_drd_get
    if _newclass:
        drd = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DataRecordDispatcherSimObject_drd_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_DataRecordDispatcherSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "DataRecordDispatcherSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DataRecordDispatcherSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DataRecordDispatcherSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DataRecordDispatcherSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DataRecordDispatcherSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_DataRecordDispatcherSimObject
    __del__ = lambda self: None
DataRecordDispatcherSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DataRecordDispatcherSimObject_swigregister
DataRecordDispatcherSimObject_swigregister(DataRecordDispatcherSimObject)

class RTSyncSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, RTSyncSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, RTSyncSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["gtod_clock"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_gtod_clock_set
    __swig_getmethods__["gtod_clock"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_gtod_clock_get
    if _newclass:
        gtod_clock = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_gtod_clock_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_gtod_clock_set)
    __swig_setmethods__["itimer"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_itimer_set
    __swig_getmethods__["itimer"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_itimer_get
    if _newclass:
        itimer = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_itimer_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_itimer_set)
    __swig_setmethods__["rt_sync"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_rt_sync_set
    __swig_getmethods__["rt_sync"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_rt_sync_get
    if _newclass:
        rt_sync = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_rt_sync_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_rt_sync_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_RTSyncSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "RTSyncSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_RTSyncSimObject
    __del__ = lambda self: None
RTSyncSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RTSyncSimObject_swigregister
RTSyncSimObject_swigregister(RTSyncSimObject)

class FrameLogSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, FrameLogSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, FrameLogSimObject, name)
    __repr__ = _swig_repr
    __swig_getmethods__["frame_log"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.FrameLogSimObject_frame_log_get
    if _newclass:
        frame_log = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.FrameLogSimObject_frame_log_get)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_FrameLogSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "FrameLogSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.FrameLogSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.FrameLogSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.FrameLogSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.FrameLogSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_FrameLogSimObject
    __del__ = lambda self: None
FrameLogSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.FrameLogSimObject_swigregister
FrameLogSimObject_swigregister(FrameLogSimObject)

class MasterSlaveSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MasterSlaveSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, MasterSlaveSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["master"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject_master_set
    __swig_getmethods__["master"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject_master_get
    if _newclass:
        master = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject_master_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject_master_set)
    __swig_setmethods__["slave"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject_slave_set
    __swig_getmethods__["slave"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject_slave_get
    if _newclass:
        slave = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject_slave_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject_slave_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_MasterSlaveSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MasterSlaveSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_MasterSlaveSimObject
    __del__ = lambda self: None
MasterSlaveSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.MasterSlaveSimObject_swigregister
MasterSlaveSimObject_swigregister(MasterSlaveSimObject)

class InstrumentationSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, InstrumentationSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, InstrumentationSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["echo_jobs"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject_echo_jobs_set
    __swig_getmethods__["echo_jobs"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject_echo_jobs_get
    if _newclass:
        echo_jobs = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject_echo_jobs_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject_echo_jobs_set)
    __swig_setmethods__["debug_pause"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject_debug_pause_set
    __swig_getmethods__["debug_pause"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject_debug_pause_get
    if _newclass:
        debug_pause = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject_debug_pause_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject_debug_pause_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_InstrumentationSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InstrumentationSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_InstrumentationSimObject
    __del__ = lambda self: None
InstrumentationSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InstrumentationSimObject_swigregister
InstrumentationSimObject_swigregister(InstrumentationSimObject)

class DMTCPSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DMTCPSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, DMTCPSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dmtcp"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DMTCPSimObject_dmtcp_set
    __swig_getmethods__["dmtcp"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DMTCPSimObject_dmtcp_get
    if _newclass:
        dmtcp = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DMTCPSimObject_dmtcp_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DMTCPSimObject_dmtcp_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_DMTCPSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "DMTCPSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DMTCPSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DMTCPSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DMTCPSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DMTCPSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_DMTCPSimObject
    __del__ = lambda self: None
DMTCPSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.DMTCPSimObject_swigregister
DMTCPSimObject_swigregister(DMTCPSimObject)

class InjectorExecSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, InjectorExecSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, InjectorExecSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["rtie"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorExecSimObject_rtie_set
    __swig_getmethods__["rtie"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorExecSimObject_rtie_get
    if _newclass:
        rtie = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorExecSimObject_rtie_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorExecSimObject_rtie_set)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_InjectorExecSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InjectorExecSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorExecSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorExecSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorExecSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorExecSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_InjectorExecSimObject
    __del__ = lambda self: None
InjectorExecSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorExecSimObject_swigregister
InjectorExecSimObject_swigregister(InjectorExecSimObject)

class InjectorSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, InjectorSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, InjectorSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["rtis"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_rtis_set
    __swig_getmethods__["rtis"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_rtis_get
    if _newclass:
        rtis = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_rtis_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_rtis_set)
    __swig_setmethods__["injector_executor_so"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_injector_executor_so_set
    __swig_getmethods__["injector_executor_so"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_injector_executor_so_get
    if _newclass:
        injector_executor_so = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_injector_executor_so_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_injector_executor_so_set)

    def create_injector_executors(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_create_injector_executors(self, *args)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_InjectorSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InjectorSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_InjectorSimObject
    __del__ = lambda self: None
InjectorSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.InjectorSimObject_swigregister
InjectorSimObject_swigregister(InjectorSimObject)

class ZeroconfSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ZeroconfSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ZeroconfSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["zc"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ZeroconfSimObject_zc_set
    __swig_getmethods__["zc"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ZeroconfSimObject_zc_get
    if _newclass:
        zc = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ZeroconfSimObject_zc_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ZeroconfSimObject_zc_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_ZeroconfSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "ZeroconfSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ZeroconfSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ZeroconfSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ZeroconfSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ZeroconfSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_ZeroconfSimObject
    __del__ = lambda self: None
ZeroconfSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.ZeroconfSimObject_swigregister
ZeroconfSimObject_swigregister(ZeroconfSimObject)

class UnitTestSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, UnitTestSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, UnitTestSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["unit_tests"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UnitTestSimObject_unit_tests_set
    __swig_getmethods__["unit_tests"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UnitTestSimObject_unit_tests_get
    if _newclass:
        unit_tests = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UnitTestSimObject_unit_tests_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UnitTestSimObject_unit_tests_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_UnitTestSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "UnitTestSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UnitTestSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UnitTestSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UnitTestSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UnitTestSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_UnitTestSimObject
    __del__ = lambda self: None
UnitTestSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UnitTestSimObject_swigregister
UnitTestSimObject_swigregister(UnitTestSimObject)

class UdUnitsSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, UdUnitsSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, UdUnitsSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["udunits"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UdUnitsSimObject_udunits_set
    __swig_getmethods__["udunits"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UdUnitsSimObject_udunits_get
    if _newclass:
        udunits = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UdUnitsSimObject_udunits_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UdUnitsSimObject_udunits_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_UdUnitsSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "UdUnitsSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UdUnitsSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UdUnitsSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UdUnitsSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UdUnitsSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_UdUnitsSimObject
    __del__ = lambda self: None
UdUnitsSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.UdUnitsSimObject_swigregister
UdUnitsSimObject_swigregister(UdUnitsSimObject)

class RocketSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, RocketSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, RocketSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["rocket"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RocketSimObject_rocket_set
    __swig_getmethods__["rocket"] = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RocketSimObject_rocket_get
    if _newclass:
        rocket = _swig_property(_m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RocketSimObject_rocket_get, _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RocketSimObject_rocket_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.new_RocketSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "RocketSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RocketSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RocketSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RocketSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RocketSimObject___len__(self, *args)
    __swig_destroy__ = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.delete_RocketSimObject
    __del__ = lambda self: None
RocketSimObject_swigregister = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.RocketSimObject_swigregister
RocketSimObject_swigregister(RocketSimObject)


def castAsSimEnvironment(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsSimEnvironment(*args)
castAsSimEnvironment = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsSimEnvironment

def castAsSysSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsSysSimObject(*args)
castAsSysSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsSysSimObject

def castAsMonteCarloSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsMonteCarloSimObject(*args)
castAsMonteCarloSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsMonteCarloSimObject

def castAsMemoryManagerSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsMemoryManagerSimObject(*args)
castAsMemoryManagerSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsMemoryManagerSimObject

def castAsCheckPointRestartSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsCheckPointRestartSimObject(*args)
castAsCheckPointRestartSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsCheckPointRestartSimObject

def castAsSieSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsSieSimObject(*args)
castAsSieSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsSieSimObject

def castAsCommandLineArgumentsSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsCommandLineArgumentsSimObject(*args)
castAsCommandLineArgumentsSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsCommandLineArgumentsSimObject

def castAsMessageSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsMessageSimObject(*args)
castAsMessageSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsMessageSimObject

def castAsJITSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsJITSimObject(*args)
castAsJITSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsJITSimObject

def castAsInputProcessorSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsInputProcessorSimObject(*args)
castAsInputProcessorSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsInputProcessorSimObject

def castAsThreadProcessEventSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsThreadProcessEventSimObject(*args)
castAsThreadProcessEventSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsThreadProcessEventSimObject

def castAsEventManagerSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsEventManagerSimObject(*args)
castAsEventManagerSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsEventManagerSimObject

def castAsVariableServerSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsVariableServerSimObject(*args)
castAsVariableServerSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsVariableServerSimObject

def castAsDataRecordDispatcherSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsDataRecordDispatcherSimObject(*args)
castAsDataRecordDispatcherSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsDataRecordDispatcherSimObject

def castAsRTSyncSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsRTSyncSimObject(*args)
castAsRTSyncSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsRTSyncSimObject

def castAsFrameLogSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsFrameLogSimObject(*args)
castAsFrameLogSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsFrameLogSimObject

def castAsMasterSlaveSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsMasterSlaveSimObject(*args)
castAsMasterSlaveSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsMasterSlaveSimObject

def castAsInstrumentationSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsInstrumentationSimObject(*args)
castAsInstrumentationSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsInstrumentationSimObject

def castAsDMTCPSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsDMTCPSimObject(*args)
castAsDMTCPSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsDMTCPSimObject

def castAsInjectorExecSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsInjectorExecSimObject(*args)
castAsInjectorExecSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsInjectorExecSimObject

def castAsInjectorSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsInjectorSimObject(*args)
castAsInjectorSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsInjectorSimObject

def castAsZeroconfSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsZeroconfSimObject(*args)
castAsZeroconfSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsZeroconfSimObject

def castAsUnitTestSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsUnitTestSimObject(*args)
castAsUnitTestSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsUnitTestSimObject

def castAsUdUnitsSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsUdUnitsSimObject(*args)
castAsUdUnitsSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsUdUnitsSimObject

def castAsRocketSimObject(*args):
    return _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsRocketSimObject(*args)
castAsRocketSimObject = _m02f6b5bb52bf319dfe0fa8bf2cbbf84b.castAsRocketSimObject
# This file is compatible with both classic and new-style classes.


