# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_meade57f199c86184507d5c153bb0ff30', [dirname(__file__)])
        except ImportError:
            import _meade57f199c86184507d5c153bb0ff30
            return _meade57f199c86184507d5c153bb0ff30
        if fp is not None:
            try:
                _mod = imp.load_module('_meade57f199c86184507d5c153bb0ff30', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _meade57f199c86184507d5c153bb0ff30 = swig_import_helper()
    del swig_import_helper
else:
    import _meade57f199c86184507d5c153bb0ff30
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _meade57f199c86184507d5c153bb0ff30.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator_equal(self, x)

    def copy(self):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator_copy(self)

    def next(self):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator_next(self)

    def __next__(self):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator___next__(self)

    def previous(self):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator_previous(self)

    def advance(self, n):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _meade57f199c86184507d5c153bb0ff30.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _meade57f199c86184507d5c153bb0ff30.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    all_keys = [attr for attr in dir(class_type) if not attr.startswith('__')and attr != '_s' ]
    data_keys = sorted(class_type.__swig_setmethods__.keys())
    method_keys = [ x for x in all_keys if x not in data_keys ]
    raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
     (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
# this line is changed to handle older swigs that used PySwigObject instead of the current SwigPyObject
        if type(value).__name__ == 'SwigPyObject' or type(value).__name__ == 'PySwigObject' :
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        all_keys = [attr for attr in dir(class_type) if not attr.startswith('__') and attr != '_s' ]
        data_keys = sorted(class_type.__swig_setmethods__.keys())
        method_keys = [ x for x in all_keys if x not in data_keys ]
        raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
         (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,1)

class ROCKET(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ROCKET, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ROCKET, name)
    __repr__ = _swig_repr

    def __getitem__(self, *args):
        return _meade57f199c86184507d5c153bb0ff30.ROCKET___getitem__(self, *args)

    def __len__(self, *args):
        return _meade57f199c86184507d5c153bb0ff30.ROCKET___len__(self, *args)
    __swig_setmethods__["init_thrust"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_init_thrust_set
    __swig_getmethods__["init_thrust"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_init_thrust_get
    if _newclass:
        init_thrust = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_init_thrust_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_init_thrust_set)
    __swig_setmethods__["vel0"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_vel0_set
    __swig_getmethods__["vel0"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_vel0_get
    if _newclass:
        vel0 = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_vel0_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_vel0_set)
    __swig_setmethods__["pos0"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_pos0_set
    __swig_getmethods__["pos0"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_pos0_get
    if _newclass:
        pos0 = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_pos0_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_pos0_set)
    __swig_setmethods__["init_angle"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_init_angle_set
    __swig_getmethods__["init_angle"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_init_angle_get
    if _newclass:
        init_angle = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_init_angle_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_init_angle_set)
    __swig_setmethods__["mass"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_mass_set
    __swig_getmethods__["mass"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_mass_get
    if _newclass:
        mass = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_mass_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_mass_set)
    __swig_setmethods__["airDensity"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_airDensity_set
    __swig_getmethods__["airDensity"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_airDensity_get
    if _newclass:
        airDensity = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_airDensity_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_airDensity_set)
    __swig_setmethods__["drag"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_drag_set
    __swig_getmethods__["drag"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_drag_get
    if _newclass:
        drag = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_drag_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_drag_set)
    __swig_setmethods__["gravityForce"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_gravityForce_set
    __swig_getmethods__["gravityForce"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_gravityForce_get
    if _newclass:
        gravityForce = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_gravityForce_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_gravityForce_set)
    __swig_setmethods__["thrust"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_thrust_set
    __swig_getmethods__["thrust"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_thrust_get
    if _newclass:
        thrust = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_thrust_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_thrust_set)
    __swig_setmethods__["acc"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_acc_set
    __swig_getmethods__["acc"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_acc_get
    if _newclass:
        acc = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_acc_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_acc_set)
    __swig_setmethods__["vel"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_vel_set
    __swig_getmethods__["vel"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_vel_get
    if _newclass:
        vel = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_vel_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_vel_set)
    __swig_setmethods__["pos"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_pos_set
    __swig_getmethods__["pos"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_pos_get
    if _newclass:
        pos = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_pos_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_pos_set)
    __swig_setmethods__["angle"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_angle_set
    __swig_getmethods__["angle"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_angle_get
    if _newclass:
        angle = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_angle_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_angle_set)
    __swig_setmethods__["time"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_time_set
    __swig_getmethods__["time"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_time_get
    if _newclass:
        time = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_time_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_time_set)
    __swig_setmethods__["impact"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_impact_set
    __swig_getmethods__["impact"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_impact_get
    if _newclass:
        impact = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_impact_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_impact_set)
    __swig_setmethods__["impactTime"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_impactTime_set
    __swig_getmethods__["impactTime"] = _meade57f199c86184507d5c153bb0ff30.ROCKET_impactTime_get
    if _newclass:
        impactTime = _swig_property(_meade57f199c86184507d5c153bb0ff30.ROCKET_impactTime_get, _meade57f199c86184507d5c153bb0ff30.ROCKET_impactTime_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _meade57f199c86184507d5c153bb0ff30.new_ROCKET()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "ROCKET", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _meade57f199c86184507d5c153bb0ff30.delete_ROCKET
    __del__ = lambda self: None
ROCKET_swigregister = _meade57f199c86184507d5c153bb0ff30.ROCKET_swigregister
ROCKET_swigregister(ROCKET)


def rocket_default_data(*args):
    return _meade57f199c86184507d5c153bb0ff30.rocket_default_data(*args)
rocket_default_data = _meade57f199c86184507d5c153bb0ff30.rocket_default_data

def rocket_init(*args):
    return _meade57f199c86184507d5c153bb0ff30.rocket_init(*args)
rocket_init = _meade57f199c86184507d5c153bb0ff30.rocket_init

def rocket_shutdown(*args):
    return _meade57f199c86184507d5c153bb0ff30.rocket_shutdown(*args)
rocket_shutdown = _meade57f199c86184507d5c153bb0ff30.rocket_shutdown
# This file is compatible with both classic and new-style classes.


